---
ssh:
  banner: "Welcome to ContainerSSH!\n"
  hostkeys:
    - /var/secrets/ssh_host_rsa_key
log:
  level: debug
auth:
  url: "http://authconfig:8080"
configserver:
  url: "http://authconfig:8080/config"
backend: docker
docker:
  connection:
    host: unix:///var/run/docker.sock
