# This file is provided as a quick way to deploy ContainerSSH for
# testing purposes. It should not be used for production.
#
# Please see the ContainerSSH reference manual for a detailed guide:
# https://containerssh.io/reference/
---
version: '3.2'
services:
  containerssh:
    build: .
    ports:
      - 127.0.0.1:2222:2222
    volumes:
    - type: bind
      source: ./config.yaml
      target: /etc/containerssh/config.yaml
    - type: bind
      source: ./ssh_host_rsa_key
      target: /var/secrets/ssh_host_rsa_key
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  authconfig:
    image: containerssh/containerssh-test-authconfig:0.3.1
