---
ssh:
  hostkeys:
    - /var/secrets/ssh_host_rsa_key
    - /var/secrets/ssh_host_ed25519_key
    - /var/secrets/ssh_host_ecdsa_key
auth:
  url: "http://authconfig:8080"
configserver:
  url: "http://authconfig:8080/config"
dockerrun:
  host: unix:///var/run/docker.sock
log:
  level: debug
